---
format: gfm
jupyter: python3
execute:
  warning: false
---

Library for virtual screening of molecules using geometry-based models.

Models are run using Atomic Simulation Environment.

Screening pipelines are constructed and run using dplutils.

Basically, this is a library of dplutils tasks, including tasks for running models with ASE and tasks for filtering the results.

# Example: Strain Energy

Beginning with a simple example that requires embedding a SMILES string as a geometry, optimizing the geometry, and computing an energy.

Input table `in.csv`:
```
mol_id,n_c,smiles
cyclohexane,6,C1CCCCC1
cyclopentane,5,C1CCCC1
cyclobutane,4,C1CCC1
cyclopropane,3,C1CC1
```

Computing the energies of each:

```python
{{< include examples/strain.py >}}
```

```{python}
#| eval: true
#| echo: false
#| output: true
import runpy
runpy.run_path('examples/strain.py')
```

The result is a table with an `energy` column:

```{python}
#| eval: true
#| echo: false
#| output: true
import pandas as pd
results = pd.concat(
    (pd.read_parquet(infile) for infile in glob("*.parquet")),
    ignore_index=True)
print(results)
```

The energy per carbon shows the trend in strain energy:

```{python}
#| eval: true
#| echo: true
#| output: true
from glob import glob
import pandas as pd
results = pd.concat(
    (pd.read_parquet(infile) for infile in glob("*.parquet")),
    ignore_index=True)
results['energy_per_c'] = results['energy'] / results['n_c']
print(results[['mol_id', 'energy_per_c']])
```

# Example: Reaction energy

This example shows what to do when the ASE calculator needs to be customized to the molecule.
We will calculate the combustion energy of methane, which requires taking into account the triplet state of oxygen.

Input table:

```
mol_id,coef,multiplicity,smiles
methane,-1,1,C
oxygen,-2,3,O=O
carbon_dioxide,1,1,O=C=O
water,2,1,O
```

Calculating energies:

```{python}
{{< include examples/combustion.py >}}
```

```{python}
#| eval: true
#| echo: false
#| output: true
import runpy
runpy.run_path('examples/combustion.py')
```

We see here that embedding can take a tuple of columns, rather than a single column, and store the information as part of the ASE Atoms object.

Then, calculating the reaction energy:

```{python}
#| eval: true
#| echo: true
#| output: true
import pandas as pd
from glob import glob
results = pd.concat(
    (pd.read_parquet(infile) for infile in glob("*.parquet")),
    ignore_index=True)
rxn_energy = (results['coef'] * results['energy']).sum()
print(rxn_energy)
```

This should be the combustion energy of methane.

# Example: Phosphorescence emission energy

Now we will consider an example where it is convenient to split the ASE action into two parts.
We will do energy calculations on the same molecule, with multiplicities 1 and 3.
It is therefore convenient to define a "setup function" that sets the calculator, and a separate "action function" that calculates the energy.

We will use [an example molecule](www.ccdc.cam.ac.uk/structures/Search?Ccdcid=KAVJOH01) displaying phosphorescence, and use the triplet energy above the ground state energy to estimate the phosphorescence emission energy.
For pipelines that read from files, usually it is convenient to begin with a table containing paths, as awkward as it seems when we're running on a single example.

```
mol_id,structure_path
irppy3,test_data/KAVJOH01.mol2
```

Then, the pipeline:

```python
{{< include examples/phosphorescence.py>}}
```

```{python}
#| eval: true
#| echo: false
#| output: true
import runpy
runpy.run_path('examples/phosphorescence.py')
```

This is calculating a vertical excitation energy; that is, both energies are calculated in the triplet geometry.

Then, taking the difference to obtain an estimate of the phosphorescence energy:

```{python}
#| eval: true
#| echo: true
#| output: true
import pandas as pd
from glob import glob
results = pd.concat(
    (pd.read_parquet(infile) for infile in glob("*.parquet")),
    ignore_index=True)
print(results['triplet_energy'] - results['ground_energy'])
```
